<?php

namespace Zephyr\CoursBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends EntityRepository
{
	public function findAllOrdered()
    {
        $qb = $this->createQueryBuilder('course')
            ->addOrderBy('course.subject', 'ASC');
        $query = $qb->getQuery();
        //Debug
        //var_dump($query->getDQL());die;
        return $query->execute();
    }
}
