<?php

namespace Zephyr\CoursBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends EntityRepository
{
	public function getSelectList()
	{
    	$qb = $this->createQueryBuilder('a')
               	   ->where('a.publication = 1');
        return $qb;
    }
}
