<?php

namespace Zephyr\CoursBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\Query;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends EntityRepository
{
    public function querySearch($query)
    {
        //Création d'un QueryBuilder
        $qb = $this->createQueryBuilder('s');
        //Récupération de l'objet Query avec le language DQL
        if($query == null) return $qb->getQuery();
        //Suppression des espaces de début et de fin de chaine
        $query = trim($query);
        //Retourne un tableau de chaine en séparant les strings d'un espace
        $words = explode(' ', $query);
        //Si l'user commencer à taper le code cantine
        if(count($words) === 1){
            //Analyse de query pour compléter le code cantine
            if(preg_match('/^[0-9]+$/', $query)) //Si c'est trouvé
                $qb
                    //On place le code en paramètre et on cherche 
                    ->where('s.id = :id')
                    ->setParameter('id', $query);
            else
                $qb
                    //On place le nom/prénom en paramètre et on cherche 
                    ->where('s.firstName LIKE :query')
                    ->orWhere('s.lastName LIKE :query')
                    ->setParameter('query', "%$query%");
        }
        else{
            //Recherche par le nom et prénom
            foreach($words as $key => $word){
                $qb
                    ->andWhere("s.firstName LIKE :query$key OR s.lastName LIKE :query$key")
                    ->setParameter("query$key", "%$word%");
            }
        }
        return $qb->getQuery();
    }

    public function search($query)
    {
        $q = $this->querySearch($query);
        try{
            //Transforme la donnée en une array PHP
            $student = $q->getSingleResult(Query::HYDRATE_ARRAY);
        }
        catch(\Exception $e){
            return null;
        }

        if(isset($student['firstName'])) $student['first_name'] = $student['firstName'];
        if(isset($student['lastName'])) $student['last_name'] = $student['lastName'];

        return $student;
    }

    public function findAsArray($id)
    {
        try{
            //Recherche par le code cantine
            $student = $this->createQueryBuilder('s')
                ->where('s.id = :id')
                ->setParameter('id', $id)
                ->getQuery()
                ->getSingleResult(Query::HYDRATE_ARRAY);
        }
        catch(NoResultException $e){
            return null;
        }

        if(isset($student['firstName'])) $student['first_name'] = $student['firstName'];
        if(isset($student['lastName'])) $student['last_name'] = $student['lastName'];
        
        return $student;
    }

    public function studentExist($id)
    {
        //Compteur d'étudiants
        return $this->createQueryBuilder('s')
            ->select('COUNT(s)')
            ->where('s.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getSingleScalarResult() == 1;
    }
}
